DROP DATABASE desafioDB;

CREATE DATABASE IF NOT EXISTS desafioDB;

USE desafioDB;

CREATE TABLE IF NOT EXISTS people (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));

INSERT INTO people (name) VALUES ('Pessoa Teste');