version: '3'

services:
  node:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: people
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "--fail", "localhost:3000/healthcheck", "||", "exit 1"]
      interval: 50s
      timeout: 30s
      retries: 5
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: people
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy-reverse-challenge/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8181:80
    depends_on:
      - node
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    internal: true
