version: '3'

services:
  nginx:
    container_name: ProxyReverse
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./proxy-reverse/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  nodejs:
    container_name: AppServer
    build:
      context: ./nodejs
    environment:
      DB_HOST: localhost
      DB_USER: fullcycle
      DB_PASSWORD: fullcycle
      DB_NAME: fullcycle
    depends_on:
      - mysql

  mysql:
    container_name: DbServer
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: fullcycle
      MYSQL_ROOT_PASSWORD: fullcycle123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      

volumes:
  mysql_data:
